name: Check code base

on:
  - push
  - pull_request

permissions: {}

jobs:
  path-filter:
    timeout-minutes: 5
    outputs:
      this: ${{steps.changes.outputs.this}}
      typescript: ${{steps.changes.outputs.typescript}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            this:
              - ./.github/workflows/check.yml
            typescript:
              - ./**/*.ts
              - package.json
              - pnpm-lock.yaml
              - tsconfig.json
              - biome.json
  check-code:
    needs: path-filter
    if: needs.path-filter.outputs.this == 'true' || needs.path-filter.outputs.typescript == 'true'
    runs-on: ubuntu-latest
    permissions: {}
    strategy:
      matrix:
        node: ["lts/*"]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Show versions
        run: |
          node --version
          pnpm --version
      - run: pnpm install
      - name: Run checker
        run: pnpm run check
  status-check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - check-code
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
